apiVersion: v1
kind: Service
metadata:
  name: image-service
spec:
 type: LoadBalancer
 ports:
  - targetPort: 50054
    port: 50054
    nodePort: 30900 
 selector:
  app: image-service
  tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: image-service
  replicas: 1
  template:
    metadata:
      labels:
        app: image-service
        tier: backend

    spec:
      containers:
      - name: backend-imageservice
        imagePullPolicy: Always
        image: panoramaiubads/image-service
        ports:
        - containerPort: 50054
      restartPolicy: Always