apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-deploy
  labels:
    app: image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
        updateTimestamp: "20210410205518106"
    spec:
      containers:
      - name: image
        image: panoramaiubads/image-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 30300
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
            memory: 2Gi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: image
  name: image-service
spec:
  selector:
    app: image
  ports:
    - protocol: TCP
      port: 30300
      targetPort: 30300
  type: ClusterIP