apiVersion: v1
kind: Service
metadata:
  name: session-service
spec:
 type: ClusterIP
 ports:
  - targetPort: 50052
    port: 50052
    nodePort: 30500 
 selector:
  app: session-service
  tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
spec:
  selector:
    matchLabels:
      app: session-service
  replicas: 1
  template:
    metadata:
      labels:
        app: session-service

    spec:
      hostNetwork: true
      nodeSelector:
        worker : "2"
      containers:
      - name: session-service
        imagePullPolicy: Always
        image: panoramaiubads/session-service
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 50052
      restartPolicy: Always