apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-deploy
  labels:
    app: session
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session
  template:
    metadata:
      labels:
        app: session
        updateTimestamp: "20210410205518106"
    spec:
      containers:
      - name: session
        image: panoramaiubads/session-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 30500
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
            memory: 2Gi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: session
  name: session-service
spec:
  selector:
    app: session
  ports:
    - protocol: TCP
      port: 30500
      targetPort: 30500
  type: ClusterIP