version: 2.1

jobs:
  build:

    docker:
      - image: circleci/openjdk:11-jdk
      - image: circleci/

    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASS
      - run: cd ./session-log-service/ && docker image build . -t session-log-service:latest && docker tag session-log-service:latest $DOCKER_USERNAME/session-log-service:latest
      - run: docker push $DOCKER_USERNAME/image-service:latest
      
      

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - session-log-service-ci
