version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASS
      - run: cd image-service/ && docker image build . -t image-service:latest && docker tag image-service:latest $DOCKER_USERNAME/image-service:latest
      - run: docker push $DOCKER_USERNAME/image-service:latest

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - image-service-ci