version: 2.1
orbs:
  node: circleci/python@1.3.3
jobs:
  build:
    docker:
      - image: circleci/python:3.8.5-buster
    steps:
      - setup_remote_docker
      - checkout
      - run: cd image-service/ && pip3 install -r requirements.txt
      - run: cd image-service/ &&  python3 -m unittest test
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASS
      - run: cd image-service/ && docker image build . -t image-service:latest && docker tag image-service:latest $DOCKER_USERNAME/image-service:latest
      - run: docker push $DOCKER_USERNAME/image-service:latest

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - image-service-ci