version: 2.1
orbs:
  node: circleci/python@1.3.3
jobs:
  build-auth-service:
    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: cd ./auth-service/ && npm install && npm run compile && npm run buildimage

  build-user-service:
    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: cd ./user-service/ && npm install && npm run compile && npm run buildimage

  build-session-service:
    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: cd ./session-service/ && npm install && npm run compile && npm run buildimage

  build-gateway-service:
    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: cd ./gateway-service/ && npm install && npm run compile && npm run buildimage

  build-image-service:
    docker:
      - image: circleci/python:3.8.5-buster
    steps:
      - setup_remote_docker
      - checkout
      - run: cd image-service/ && pip3 install -r requirements.txt
      - run: cd image-service/ &&  python3 -m unittest test
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASS
      - run: cd image-service/ && docker image build . -t image-service:latest && docker tag image-service:latest $DOCKER_USERNAME/image-service:latest
      - run: docker push $DOCKER_USERNAME/image-service:latest

  build-react-ui:
    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASS
      - run: cd panorama-ui/react-ui/ && docker image build . -t react-ui:latest && docker tag react-ui:latest $DOCKER_USERNAME/react-ui:latest
      - run: docker push $DOCKER_USERNAME/react-ui:latest
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - image-service-ci
