version: 2.1
orbs:
  node: circleci/python@1.3.3
jobs:
  build:

    docker:
      - image: circleci/python:3.8.5-buster
    steps:
      - setup_remote_docker
      - checkout
      - run: cd ./auth-service/ && npm install
      - run: cd ./auth-service/ && npm run test
      - run: cd ./auth-service/ && npm run compile
      - run: cd ./auth-service/ && npm run buildimage

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - auth-service-ci
