version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker: 
      - image: circleci/node:buster
    steps:
      - checkout
      - run: cd ./auth-service/
      - run: ls
      - run: npm install
      - run: npm run compile


workflows:
  build:
    jobs:
      - build