version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.0.0

jobs:
  run-task:
    docker:
      - image: ''
    steps:
      - aws-ecs/run-task:
          awsvpc: false
          cluster: 'ReactAppTestCluster'
          launch-type: EC2
          task-definition: 'reactapp'

workflows:
  build-and-deploy:
    jobs:
    - aws-ecr/build-and-push-image:
        repo: "panorama-ecr"
        tag: "${CIRCLE_SHA1}"
        dockerfile: "panorama-ui/react-ui/Dockerfile"
        path: .
    - aws-ecs/deploy-service-update:
        cluster-name: 'ReactAppTestCluster'
        container-image-name-updates: 'container=reactui-service,tag=${CIRCLE_SHA1}'
        family: 'reactui-service'
        requires:
          - aws-ecr/build-and-push-image   
    - run-task:
     


