version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:

    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: cd ./auth-service/ && npm install
      - run: cd ./auth-service/ && npm run test
      - run: cd ./auth-service/ && npm run compile
      - run: cd ./auth-service/ && npm run buildimage

  build-react-ui:
    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASS
      - run: cd panorama-ui/react-ui/ && docker image build . -t react-ui:latest && docker tag react-ui:latest $DOCKER_USERNAME/react-ui:latest
      - run: docker push $DOCKER_USERNAME/react-ui:latest
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - auth-service-ci
