version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:

    docker:
      - image: circleci/node:buster
    steps:
      - setup_remote_docker
      - checkout
      - run: cd ./user-service/ && npm install
      - run: cd ./user-service/ && npm run test
      - run: cd ./user-service/ && npm run compile
      - run: cd ./user-service/ && npm run buildimage

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - user-service-ci
