version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker: 
      - image: circleci/node:buster
    steps:
      - run: git checkout dev
      - run: cd auth-service
      - run: npm install
      - run: npm run compile


workflows:
  build:
    jobs:
      - build