version: 2.1
orbs:
   maven: circleci/maven@0.0.12
jobs:
  build:

    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - setup_remote_docker
      - checkout
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASS
      - run: mvn clean install
      - run: cd ./session-log-service/ && docker image build . -t session-log-service:latest && docker tag session-log-service:latest $DOCKER_USERNAME/session-log-service:latest
      - run: docker push $DOCKER_USERNAME/session-log-service:latest

      # - run:
      #     name: Save test results
      #     command: |
      #       mkdir -p ~/test-results/junit/
      #       find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
      #     when: always
      # - store_test_results:
      #     path: ~/test-results
      # - store_artifacts:
      #     path: ~/test-results/junit
      
      

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - session-log-service-ci
