apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-log-deploy
  labels:
    app: session-log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-log
  template:
    metadata:
      labels:
        app: session-log
        updateTimestamp: "20210410205518106"
    spec:
      containers:
      - name: session-log
        image: panoramaiubads/session-log-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 30400
        env:
         - name: MONGO_URI_SYSTEM
           value: "mongodb+srv://User3:Password3@cluster0.0qdgg.mongodb.net/panorama?retryWrites=true&w=majority"
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
            memory: 2Gi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: session-log
  name: session-log-service
spec:
  selector:
    app: session-log
  ports:
    - protocol: TCP
      port: 30400
      targetPort: 30400
  type: ClusterIP