apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
 type: LoadBalancer
 ports:
  - targetPort: 50050
    port: 50050
    nodePort: 30100
 selector:
  app: app
  tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
        tier: backend

    spec:
      containers:
      - name: backend-authservice
        imagePullPolicy: Always
        image: panoramaiubads/auth-service
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 50050
      restartPolicy: Always