apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        updateTimestamp: "20210410205518106"
    spec:
      containers:
      - name: auth
        image: panoramaiubads/auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 30100
        env:
         - name: Mongo_uri_auth
           value: "mongodb+srv://User1:Password1@cluster0.vpy8b.mongodb.net/panorama?retryWrites=true&w=majority"
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
            memory: 2Gi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 30100
      targetPort: 30100
  type: ClusterIP