apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
 type: LoadBalancer
 ports:
  - targetPort: 50051
    port: 50051
    nodePort: 30100 
 selector:
  app: app
  tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
        tier: backend

    spec:
      containers:
      - name: backend-authservice
        imagePullPolicy: Always
        image: panoramaiubads/auth-service
        ports:
        - containerPort: 50051
        env:
         - name: Mongo_uri_auth
           value: "mongodb+srv://User1:Password1@cluster0.vpy8b.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
      restartPolicy: Always