apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        updateTimestamp: "20210410205518106"
    spec:
      containers:
      - name: auth
        image: panoramaiubads/auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
            memory: 2Gi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth-service
spec:
  selector:
    app: auth
  ports:
      port: 50051
      targetPort: 50051
  type: ClusterIP