apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
 type: LoadBalancer
 ports:
  - targetPort: 50053
    port: 50053
    nodePort: 30600 
 selector:
  app: user-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:
      - name: user-service
        imagePullPolicy: Always
        image: panoramaiubads/user-service
        resources:
        ports:
        - containerPort: 50053
        env:
         - name: Mongo_uri_user
           value: "mongodb+srv://User2:Password2@cluster0.1pzuq.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
      restartPolicy: Always