apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
 type: LoadBalancer
 ports:
  - targetPort: 50075
    port: 50075
    nodePort: 30600 
 selector:
  app: app
  tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
        tier: backend

    spec:
      containers:
      - name: backend-session
        imagePullPolicy: Always
        image: panoramaiubads/user-service
        resources:
        ports:
        - containerPort: 50075
      restartPolicy: Always