apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
 type: ClusterIP
 ports:
  - targetPort: 30600
    port: 30600
    # nodePort: 30600 
 selector:
  app: user-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service

    spec:
      hostNetwork: true
      nodeSelector:
        worker : "2"
      containers:
      - name: user-service
        imagePullPolicy: Always
        image: panoramaiubads/user-service
        resources:
        ports:
        - containerPort: 30600
        env:
         - name: Mongo_uri_user
           value: "mongodb+srv://User2:Password2@cluster0.1pzuq.mongodb.net/panorama?retryWrites=true&w=majority"
         - name: userServicePort
           value: "30600"
        
      restartPolicy: Always