apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
        updateTimestamp: "20210410205518106"
    spec:
      containers:
      - name: user
        image: panoramaiubads/user-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 30600
        env:
         - name: Mongo_uri_user
           value: "mongodb+srv://User2:Password2@cluster0.1pzuq.mongodb.net/panorama?retryWrites=true&w=majority"
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
            memory: 2Gi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user
  name: user-service
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 30600
      targetPort: 30600
  type: ClusterIP