apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        updateTimestamp: "20210410205518106"
    spec:
      containers:
      - name: gatewaygit 
        image: panoramaiubads/gateway-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
            memory: 2Gi
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - nodePort: 30200
      port: 3000
      targetPort: 3000
  type: LoadBalancer