apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
 type: LoadBalancer
 ports:
  - targetPort: 3000
    port: 3000
    nodePort: 30200 
 selector:
  app: gateway-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deploy
  labels:
    app: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway-service
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service

    spec:
      hostNetwork: true
      containers:
      - name: gateway-service
        imagePullPolicy: Always
        image: panoramaiubads/gateway-service:latest
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
            memory: 2Gi
        ports:
        - containerPort: 3000
      restartPolicy: Always
