apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
 type: LoadBalancer
 ports:
  - targetPort: 3001
    port: 3001
    nodePort: 31200 
 selector:
  app: gateway-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway-service
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service

    spec:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: worker
                operator: In
                values:
                - "1"  
      containers:
      - name: backend-gatewayservice
        imagePullPolicy: Always
        image: panoramaiubads/gateway-service
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3000
        
        env:
         - name: authServerIP 
           value: "http://149.165.157.30"
         - name: authServicePort
           value: "31100"
         - name: sessionServerIP 
           value: "http://149.165.156.181"
         - name: sessionServicePort
           value: "31300"
         - name: userServerIP
           value: "http://149.165.157.30"
         - name: userServicePort
           value: "31600"
         - name: imageServerIP
           value: "http://149.165.156.181"
         - name: imageServicePort 
           value: "31900"
         - name: sessionLogServerIP
           value: "http://149.165.157.30"
         - name: sessionLogServicePort 
           value: "31400"
         - name: gatewayServerIP 
           value: "http://149.165.156.181"
         - name: gatewayServicePort 
           value: "31200"
      restartPolicy: Always
