apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
 type: LoadBalancer
 ports:
  - targetPort: 3000
    port: 3000
    nodePort: 30200 
 selector:
  app: gateway-service
  tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: gateway-service
  replicas: 2
  template:
    metadata:
      labels:
        app: gateway-service
        tier: backend

    spec:
      containers:
      - name: backend-gatewayservice
        imagePullPolicy: Always
        image: panoramaiubads/gateway-service
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3000
        env:
         - name: authServerIP
           value: "http://auth-service"
         - name: userServerIP
           value: "http://user-service"
         - name: sessionServerIP
           value: "http://session-service"
         - name: imageServerIP
           value: "http://image-service"
         - name: sessionLogServerIP
           value: "http://session-log-service"
         
         - name: authServiceIP
           value: "30100"
         - name: userServiceIP
           value: "30600"
         - name: imageServiceIP
           value: "30900"
         - name: sessionServiceIP
           value: "30300"
         - name: sessionLogServiceIP
           value: "30400"

           
         - name: auth-service
           value: "http://auth-service:30100"
         - name: image-service
           value: "http://image-service:30900"
         - name: session-log-service
           value: "http://session-log-service:30400"
         - name: session-service
           value: "http://session-service:30300"
         - name: user-service
           value: "http://user-service:30600"
      restartPolicy: Always