apiVersion: v1
kind: Service
metadata:
  name: react-ui
spec:
 type: LoadBalancer
 ports:
  - targetPort: 80
    port: 80
    nodePort: 8000
 selector:
  app: app
  tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
        tier: frontend

    spec:
      containers:
      - name: frontend-reactui
        imagePullPolicy: Always
        image: panoramaiubads/react-ui
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
      restartPolicy: Always