apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: react-ui
  name: react-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      containers:
      - image: panoramaiubads/react-ui
        name: react-ui
        imagePullPolicy: Always
        ports:
        - containerPort: 30800
        env:
         - name: gatewayServerIP 
           value: "http://gateway-service"
         - name: gatewayServicePort 
           value: "30200"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-ui
  name: react-ui
spec:
  type: LoadBalancer
  ports:
  - port: 30800
    targetPort: 30800
    nodePort: 30800
  selector:
    app: react-ui