apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: react-ui
  name: react-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      nodeSelector:
        worker : 1
      containers:
      - image: panoramaiubads/react-ui
        name: react-ui
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
         - name: gateway-service
           value: "http://gateway-service:3000"
         - name: gatewayServerIP 
           value: "http://149.165.156.181"
         - name: gatewayServicePort 
           value: "30200"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-ui
  name: react-ui
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30800
  selector:
    app: react-ui