apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: react-ui
  name: react-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      containers:
      - image: panoramaiubads/react-ui
        name: react-ui
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
         - name: ui_gateway
           value: http://gateway-service:3000
      
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-ui
  name: react-ui
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30100
  selector:
    app: react-ui